type BicycleType = {
  [_id?: string]: any;
  [fullName: string]: any;
  [category: string]: any;
  [novelty: boolean]: any;
  [manufacturer: string]: any;
  [article: string]: any;
  [image: string]: any;
  [availability: boolean]: any;
  [price: number]: any;
  [priceSale: number]: any;
  size: string[];
  color: string[];
  description: string;
  year: number;
  diameter: string;
  material: string;
  tires?: string;
  frame?: string;
  saddle?: string;
  seatpost?: string;
  fork?: string;
  chain?: string;
  brake?: string;
  speed?: number;
  garantine?: number;
  user?: any;
  __v?: number;
  updatedAt?: string;
};
